# Generated by Django 5.2.8 on 2026-02-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectlog',
            name='defect_prob',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='defectlog',
            name='nodefect_prob',
            field=models.FloatField(default=0.0),
        ),
    ]
